services:
  recommendation-service:
    container_name: book-recommendation-service
    build:
      context: ./book-recommendation-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./book-recommendation-service:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: