services:
  recommendation-service:
    container_name: book-recommendation-service
    build:
      context: ./book-recommendation-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  web-scraper-service:
    container_name: web-scraper-service
    build:
      context: ./web-scraper-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - scraper-data:/app/data

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - RECOMMENDATION_SERVICE_URL=http://book-recommendation-service:3000
      - SCRAPER_SERVICE_URL=http://web-scraper-service:5000
    depends_on:
      - recommendation-service
      - web-scraper-service

volumes:
  scraper-data:
