services:
  recommendation-service:
    container_name: book-recommendation-service
    build:
      context: ./book-recommendation-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - book-rec-network
    restart: always

  web-scraper-service:
    container_name: web-scraper-service
    build:
      context: ./web-scraper-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - scraper-data:/app/data
    networks:
      - book-rec-network
    restart: always

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - RECOMMENDATION_SERVICE_URL=http://book-recommendation-service:3000
      - SCRAPER_SERVICE_URL=http://web-scraper-service:5000
    depends_on:
      - recommendation-service
      - web-scraper-service
    networks:
      - book-rec-network
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gateway
    environment:
      - NODE_ENV=production
    networks:
      - book-rec-network
    restart: always

networks:
  book-rec-network:
    driver: bridge

volumes:
  scraper-data:
